#!/usr/bin/env python3
"""Generate the machine-owned rdma_subsystem onboard checklist."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

BANNER = """<!--
DO NOT EDIT BY HAND. This file is generated by
test_plan/scripts/update_checklist.py from artifacts under
test_plan/evidence/. Any hand-edit is overwritten and rejected by CI.
-->
"""

CHAIN_NAMES = (
    "bring_up",
    "counter_chain",
    "rate_chain",
    "latency",
    "offline_chain",
    "offline_analysis",
)

TRAFFIC_CHAINS = (
    "counter_chain",
    "rate_chain",
    "latency",
    "offline_chain",
    "offline_analysis",
)

CHAIN_ALIASES = {
    "BU": "bring_up",
    "BRINGUP": "bring_up",
    "BRING_UP": "bring_up",
    "CP-BU": "bring_up",
    "C": "counter_chain",
    "CP-C": "counter_chain",
    "COUNTER": "counter_chain",
    "COUNTER_CHAIN": "counter_chain",
    "E1": "counter_chain",
    "R": "rate_chain",
    "CP-R": "rate_chain",
    "RATE": "rate_chain",
    "RATE_CHAIN": "rate_chain",
    "E2": "rate_chain",
    "L": "latency",
    "CP-L": "latency",
    "LATENCY": "latency",
    "E3": "latency",
    "O": "offline_chain",
    "CP-O": "offline_chain",
    "OFFLINE": "offline_chain",
    "OFFLINE_CHAIN": "offline_chain",
    "E4": "offline_chain",
    "A": "offline_analysis",
    "CP-A": "offline_analysis",
    "ANALYSIS": "offline_analysis",
    "OFFLINE_ANALYSIS": "offline_analysis",
}

CHAIN_STAGE_PREFIX = {
    "bring_up": "BU",
    "counter_chain": "C",
    "rate_chain": "R",
    "latency": "L",
    "offline_chain": "O",
    "offline_analysis": "A",
}

MODE_NAMES = ("A", "B", "C")
MASK_NAMES = tuple(f"M{i}" for i in range(8))
RATE_NAMES = tuple(f"R{i}" for i in range(1, 5))


@dataclass(frozen=True)
class MatrixRow:
    cohort: str
    matrix_id: str
    chain: str
    mode: str
    mask: str
    rate: str
    source: str = "emulator"
    optional: bool = False


@dataclass
class EvidenceResult:
    cohort: str
    matrix_id: str
    chain: str
    status: str
    stage: str
    detail: str
    updated_at: str
    path: str


def traffic_point(cohort: str, mode: str, mask: str, rate: str) -> str:
    return f"{cohort}_{mode}_{mask}_{rate}"


def expected_rows() -> list[MatrixRow]:
    rows: list[MatrixRow] = [
        MatrixRow("S0", "S0_BU", "bring_up", "-", "-", "-", "emulator", False)
    ]

    def add_point(
        cohort: str,
        matrix_id: str,
        mode: str,
        mask: str,
        rate: str,
        source: str = "emulator",
        optional: bool = False,
    ) -> None:
        for chain in TRAFFIC_CHAINS:
            rows.append(MatrixRow(cohort, matrix_id, chain, mode, mask, rate, source, optional))

    add_point("S1", "S1_A_M4_R1", "A", "M4", "R1")
    add_point("S2", "S2_A_M0_R1", "A", "M0", "R1")

    for mask in MASK_NAMES:
        add_point("S3", traffic_point("S3", "A", mask, "R1"), "A", mask, "R1")
    for mask in MASK_NAMES:
        add_point("S4", traffic_point("S4", "B", mask, "R1"), "B", mask, "R1")
    for mask in MASK_NAMES:
        add_point("S5", traffic_point("S5", "C", mask, "R1"), "C", mask, "R1")
    for rate in RATE_NAMES:
        add_point("S6", traffic_point("S6", "A", "M0", rate), "A", "M0", rate)
    for mode in MODE_NAMES:
        for mask in MASK_NAMES:
            for rate in RATE_NAMES:
                add_point("S7", traffic_point("S7", mode, mask, rate), mode, mask, rate)
    for mode in ("A", "B"):
        for mask in MASK_NAMES:
            for rate in RATE_NAMES:
                matrix_id = f"S10_REAL_{mode}_{mask}_{rate}"
                add_point("S10", matrix_id, mode, mask, rate, "real_mutrig", True)

    return rows


def normalize_chain(raw: Any) -> str | None:
    if raw is None:
        return None
    text = str(raw).strip()
    if not text:
        return None
    upper = text.upper().replace("-", "_")
    if text in CHAIN_NAMES:
        return text
    return CHAIN_ALIASES.get(upper) or CHAIN_ALIASES.get(text.upper())


def infer_cohort(matrix_id: str) -> str:
    if matrix_id.startswith("S10_"):
        return "S10"
    match = re.match(r"^(S\d+)", matrix_id)
    if match:
        return match.group(1)
    return "UNKNOWN"


def normalize_stage(chain: str, raw: Any) -> str:
    if raw is None:
        return ""
    stage = str(raw).strip()
    if not stage:
        return ""
    stage = stage.upper().replace("_", "-")
    if stage.startswith("FAIL-AT-"):
        stage = stage[len("FAIL-AT-") :]
    if stage.startswith("FAIL_AT_"):
        stage = stage[len("FAIL_AT_") :]
    if stage.startswith("CP-"):
        stage = stage[3:]
    if re.fullmatch(r"\d+", stage):
        stage = f"{CHAIN_STAGE_PREFIX[chain]}{stage}"
    return stage.replace("-", "")


def normalize_status(chain: str, data: dict[str, Any]) -> tuple[str, str]:
    raw_status = data.get("status")
    raw_stage = data.get("stage") or data.get("fail_stage") or data.get("failed_stage")
    if raw_status is None and "pass" in data:
        raw_status = "PASS" if data.get("pass") else "FAIL"
    if raw_status is None and "ok" in data:
        raw_status = "PASS" if data.get("ok") else "FAIL"
    if raw_status is None and data.get("failures"):
        raw_status = "FAIL"
    if raw_status is None:
        raw_status = "PENDING"

    status = str(raw_status).strip().upper().replace("-", "_")
    if status in {"PASS", "PASSED", "OK"}:
        return "PASS", normalize_stage(chain, raw_stage)
    if status in {"PENDING", "NOT_RUN", "NOTRUN"}:
        return "PENDING", ""
    if status in {"SKIP", "SKIPPED", "WAIVED"}:
        return "SKIP", normalize_stage(chain, raw_stage)
    if status.startswith("FAIL_AT_"):
        stage = normalize_stage(chain, status[len("FAIL_AT_") :])
        return f"FAIL_AT_{stage}", stage
    if status.startswith("FAIL"):
        stage = normalize_stage(chain, raw_stage)
        if not stage:
            stage = CHAIN_STAGE_PREFIX[chain]
        return f"FAIL_AT_{stage}", stage
    return status, normalize_stage(chain, raw_stage)


def best_timestamp(data: dict[str, Any]) -> str:
    for key in ("updated_at", "generated_at", "collected_at", "run_ended_at", "run_started_at"):
        value = data.get(key)
        if value:
            return str(value)
    return ""


def extract_detail(data: dict[str, Any]) -> str:
    for key in ("detail", "summary", "reason", "message", "note"):
        value = data.get(key)
        if value:
            return str(value).replace("\n", " ")
    failures = data.get("failures")
    if isinstance(failures, list) and failures:
        return str(failures[0]).replace("\n", " ")
    return ""


def enforce_real_traffic_gate(
    data: dict[str, Any], chain: str, status: str, stage: str, detail: str
) -> tuple[str, str, str]:
    if chain not in TRAFFIC_CHAINS or status != "PASS":
        return status, stage, detail
    if str(data.get("mode", "-")) in {"-", ""} or str(data.get("rate", "-")) in {"-", ""}:
        return status, stage, detail
    if data.get("real_traffic") is True or "real_traffic=1" in detail:
        return status, stage, detail
    if data.get("evidence_kind") == "run_ledger":
        zero_detail = "opq_w_d=0" in detail or "bytes_w_d=0" in detail or "rqe_d=0" in detail
        if zero_detail or "run=1s" in detail:
            return (
                "FAIL_AT_C1",
                "C1",
                "legacy zero-traffic run_ledger PASS rejected; missing positive FEB/rate_emulator delta",
            )
        return (
            "FAIL_AT_C1",
            "C1",
            "run_ledger traffic PASS rejected; missing real_traffic=1 first-stage proof",
        )
    return status, stage, detail


def evidence_items_from_json(
    path: Path, evidence_root: Path, data: dict[str, Any]
) -> list[EvidenceResult]:
    rel = path.relative_to(evidence_root).as_posix()
    matrix_id = str(data.get("matrix_id") or data.get("cp_id") or path.parent.name)
    cohort = str(data.get("cohort") or infer_cohort(matrix_id))
    items: list[EvidenceResult] = []

    chain_map = data.get("chains") or data.get("chain_results")
    if isinstance(chain_map, dict):
        for raw_chain, chain_data in chain_map.items():
            chain = normalize_chain(raw_chain)
            if chain is None:
                continue
            merged: dict[str, Any] = dict(data)
            if isinstance(chain_data, dict):
                merged.update(chain_data)
            else:
                merged["status"] = chain_data
            status, stage = normalize_status(chain, merged)
            detail = extract_detail(merged)
            status, stage, detail = enforce_real_traffic_gate(merged, chain, status, stage, detail)
            items.append(
                EvidenceResult(
                    str(merged.get("cohort") or cohort),
                    str(merged.get("matrix_id") or matrix_id),
                    chain,
                    status,
                    stage,
                    detail,
                    best_timestamp(merged),
                    rel,
                )
            )

    list_items = data.get("evidence")
    if isinstance(list_items, list):
        for entry in list_items:
            if not isinstance(entry, dict):
                continue
            chain = normalize_chain(entry.get("chain"))
            if chain is None:
                continue
            merged = dict(data)
            merged.update(entry)
            status, stage = normalize_status(chain, merged)
            detail = extract_detail(merged)
            status, stage, detail = enforce_real_traffic_gate(merged, chain, status, stage, detail)
            items.append(
                EvidenceResult(
                    str(merged.get("cohort") or cohort),
                    str(merged.get("matrix_id") or matrix_id),
                    chain,
                    status,
                    stage,
                    detail,
                    best_timestamp(merged),
                    rel,
                )
            )

    direct_chain = normalize_chain(data.get("chain") or data.get("checkpoint_chain"))
    if direct_chain is not None:
        status, stage = normalize_status(direct_chain, data)
        detail = extract_detail(data)
        status, stage, detail = enforce_real_traffic_gate(data, direct_chain, status, stage, detail)
        items.append(
            EvidenceResult(
                cohort,
                matrix_id,
                direct_chain,
                status,
                stage,
                detail,
                best_timestamp(data),
                rel,
            )
        )

    return items


def json_files(evidence_root: Path) -> list[Path]:
    if not evidence_root.exists():
        return []
    return sorted(path for path in evidence_root.rglob("*.json") if path.is_file())


def load_evidence(evidence_root: Path) -> tuple[dict[tuple[str, str, str], EvidenceResult], str, str]:
    files = json_files(evidence_root)
    digest = hashlib.sha256()
    results: dict[tuple[str, str, str], EvidenceResult] = {}
    timestamps: list[str] = []

    for path in files:
        rel = path.relative_to(evidence_root).as_posix()
        payload = path.read_bytes()
        digest.update(rel.encode("utf-8"))
        digest.update(b"\0")
        digest.update(payload)
        digest.update(b"\0")
        try:
            data = json.loads(payload.decode("utf-8"))
        except json.JSONDecodeError as exc:
            raise SystemExit(f"ERROR: invalid JSON evidence {path}: {exc}") from exc
        if not isinstance(data, dict):
            raise SystemExit(f"ERROR: JSON evidence {path} must contain an object")
        for item in evidence_items_from_json(path, evidence_root, data):
            if item.chain not in CHAIN_NAMES:
                continue
            key = (item.cohort, item.matrix_id, item.chain)
            old = results.get(key)
            if old is None or (item.updated_at, item.path) >= (old.updated_at, old.path):
                results[key] = item
            if item.updated_at:
                timestamps.append(item.updated_at)

    generated_at = max(timestamps) if timestamps else "1970-01-01T00:00:00Z"
    return results, digest.hexdigest(), generated_at


def md_escape(text: Any) -> str:
    clean = str(text)
    clean = clean.replace("\n", " ")
    clean = clean.replace("|", "\\|")
    return clean


def render_checklist(evidence_root: Path) -> str:
    rows = expected_rows()
    evidence, evidence_sha, generated_at = load_evidence(evidence_root)

    expected_keys = {(row.cohort, row.matrix_id, row.chain) for row in rows}
    pass_count = fail_count = pending_count = skip_count = 0
    body: list[str] = [BANNER.rstrip(), "", "# rdma_subsystem Onboard CHECKLIST", ""]
    body.append("Generated from JSON evidence under `test_plan/evidence/`.")
    body.append("")
    body.append("## Summary")
    body.append("")

    rendered_rows: list[str] = []
    for row in rows:
        key = (row.cohort, row.matrix_id, row.chain)
        result = evidence.get(key)
        status = result.status if result else "PENDING"
        if status == "PASS":
            pass_count += 1
        elif status.startswith("FAIL"):
            fail_count += 1
        elif status == "SKIP":
            skip_count += 1
        else:
            pending_count += 1
        evidence_path = result.path if result else "-"
        updated_at = result.updated_at if result and result.updated_at else "-"
        detail = result.detail if result and result.detail else "-"
        rendered_rows.append(
            "| {cohort} | {matrix_id} | {chain} | {mode} | {mask} | {rate} | {source} | {optional} | {status} | {evidence} | {updated} | {detail} |".format(
                cohort=row.cohort,
                matrix_id=row.matrix_id,
                chain=row.chain,
                mode=row.mode,
                mask=row.mask,
                rate=row.rate,
                source=row.source,
                optional="yes" if row.optional else "no",
                status=md_escape(status),
                evidence=md_escape(evidence_path),
                updated=md_escape(updated_at),
                detail=md_escape(detail),
            )
        )

    total = pass_count + fail_count + pending_count + skip_count
    body.extend(
        [
            "| Metric | Value |",
            "|--------|-------|",
            f"| total_rows | {total} |",
            f"| pass_rows | {pass_count} |",
            f"| fail_rows | {fail_count} |",
            f"| pending_rows | {pending_count} |",
            f"| skip_rows | {skip_count} |",
            f"| json_evidence_sha256 | `{evidence_sha}` |",
            f"| generated_at | `{generated_at}` |",
            "",
            "## Keyed Rows",
            "",
            "| Cohort | Matrix ID | Chain | Mode | Mask | Rate | Source | Optional | Status | Evidence | Updated | Detail |",
            "|--------|-----------|-------|------|------|------|--------|----------|--------|----------|---------|--------|",
        ]
    )
    body.extend(rendered_rows)

    extra_keys = sorted(set(evidence) - expected_keys)
    if extra_keys:
        body.extend(
            [
                "",
                "## Unexpected Evidence Rows",
                "",
                "| Cohort | Matrix ID | Chain | Status | Evidence | Updated | Detail |",
                "|--------|-----------|-------|--------|----------|---------|--------|",
            ]
        )
        for key in extra_keys:
            result = evidence[key]
            body.append(
                "| {cohort} | {matrix_id} | {chain} | {status} | {evidence} | {updated} | {detail} |".format(
                    cohort=result.cohort,
                    matrix_id=result.matrix_id,
                    chain=result.chain,
                    status=md_escape(result.status),
                    evidence=md_escape(result.path),
                    updated=md_escape(result.updated_at or "-"),
                    detail=md_escape(result.detail or "-"),
                )
            )

    body.extend(
        [
            "",
            "## Special Cohorts",
            "",
            "- S8 math review is tracked by `test_plan/MATH_REVIEW.md`.",
            "- S9 final signoff is `test_plan/scripts/ci_verify_checklist.sh`.",
            "- S10 real-MuTRiG rows are optional and do not block the main emulator pass.",
            "",
        ]
    )

    body_text = "\n".join(body)
    checklist_sha = hashlib.sha256(body_text.encode("utf-8")).hexdigest()
    trailer = (
        f"<!-- evidence_sha256: {evidence_sha}; checklist_sha256: {checklist_sha}; "
        f"generated_at: {generated_at} -->"
    )
    return body_text + trailer + "\n"


def write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f".{path.name}.tmp.{os.getpid()}")
    tmp.write_text(content, encoding="utf-8")
    os.replace(tmp, path)


def list_cohort(cohort: str) -> int:
    rows = expected_rows()
    seen: set[str] = set()
    for row in rows:
        if row.cohort != cohort:
            continue
        if row.matrix_id in seen:
            continue
        seen.add(row.matrix_id)
        print("\t".join([row.cohort, row.matrix_id, row.mode, row.mask, row.rate, row.source]))
    return 0 if seen else 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="test_plan/CHECKLIST.md", help="output path or '-'")
    parser.add_argument("--evidence", default="test_plan/evidence", help="evidence tree")
    parser.add_argument("--list-cohort", help="print cohort matrix points and exit")
    args = parser.parse_args()

    if args.list_cohort:
        return list_cohort(args.list_cohort)

    content = render_checklist(Path(args.evidence))
    if args.out == "-":
        sys.stdout.write(content)
    else:
        write_atomic(Path(args.out), content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
